# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy software

global:
  image: node:16
  trigger:
    push:
      branches:
        - main

jobs:

  - name: build
    commands:
      - npm install
      - npx hardhat build
    artifacts:
      - name: my-build
        path: .

  - name: test
    commands:
      - npx hardhat test
    resources:
      - name: my-build

  - name: deploy
    commands:
      - echo "deploying..."
    resources:
      - name: my-build
