# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy software

global:
  image: alpine
  trigger:
    push:
      branches:
        - main

jobs:

  - name: build
    commands:
      - npx hardhat compile
    artifacts:
      - name: artifacts

  - name: test
    commands:
      - ls -R artifacts
    resources:
      - name: artifacts

  - name: deploy
    commands:
      - echo "deploying..."
    resources:
      - name: artifacts
